---
# Tasks for the Apache role
- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Start and enable Apache service
  service:
    name: apache2
    state: started
    enabled: true

- name: Copy the Apache configuration file
  template:
    src: httpd.conf.j2
    dest: /etc/apache2/conf-available/javascript-common.conf
  notify: restart apache

