- name: Provision ntp service
  hosts: all
  become: yes
  tasks:
    - name: Install ntp agent on CentOS
      yum:
        name: crony
        state: present
      when: ansible_distribution == "CentOS"
    - name: Install ntp agent on Ubuntu
      apt:
        name: ntp
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Start ntp service on CentOS
      service:
        name: crony
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"
    - name: Start ntp service on Ubuntu
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"
